### ISSUE TITLE
关于复现时的一个问题

### ISSUE THREAD

**Issue by xia-zhe** [GeWu-Lab/MUSIC-AVQA#7]
您好，感谢您的出色工作，请问我在训练时出现这样一个错误是什么原因呢？谢谢！：
Traceback (most recent call last):
  File "net_grd_avst/main_avst.py", line 275, in <module>
    main()
  File "net_grd_avst/main_avst.py", line 258, in main
    train(args, model, train_loader, optimizer, criterion, epoch=epoch)
  File "net_grd_avst/main_avst.py", line 46, in train
    for batch_idx, sample in enumerate(train_loader):
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/uestcers/uestc1/.conda/envs/music/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [11, 512, 14, 14] at entry 0 and [10, 512, 14, 14] at entry 1

此问题已解决！之前我直接用了the extracted frames (1fps)，但是这里面提取的帧数有62和60的，我重新在原视频中提取后得到的就是60的了。

**Comment by xia-zhe** [comment]
还有一个问题，在训练时是要按着这个顺序吗？：
1、：python net_grd_avst/main_avst.py
2、：python grounding_gen/main_grd_gen.py
3、：python net_grd_avst/main_avst.py
为什么要训练两次main_avst.py呢？
